apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    purpose: debug
spec:
  containers:
  - name: debian
    image: debian:stable-slim    
    command: ["sleep"]
    args: ["3600"]
    tty: true
    stdin: true

